name: build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - RELEASE_PACKAGE: gitlab-ce
            RELEASE_VERSION: 15.11.7-ce.0
            PUSH_TAGS: 15.11.7-ce.0,15.11.7-ce,15.11-ce,15-ce,ce
          - RELEASE_PACKAGE: gitlab-ee
            RELEASE_VERSION: 15.11.7-ee.0
            PUSH_TAGS: 15.11.7-ee.0,15.11.7-ee,15.11-ee,15-ee,ee,latest-15,latest
          - RELEASE_PACKAGE: gitlab-ce
            RELEASE_VERSION: 16.0.2-ce.0
            PUSH_TAGS: 16.0.2-ce.0,16.0.2-ce,16.0-ce,16-ce
          - RELEASE_PACKAGE: gitlab-ee
            RELEASE_VERSION: 16.0.2-ee.0
            PUSH_TAGS: 16.0.2-ee.0,16.0.2-ee,16.0-ee,16-ee,latest-16

    steps:
      - uses: actions/checkout@v2

      - name: docker login to docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Must set write access in the package settings
      # See: https://github.com/docker/build-push-action/issues/463#issuecomment-924995909
      - name: docker login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup binfmt-support
        uses: docker/setup-qemu-action@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate tags
        id: generate-tags
        run: |
          dockerio_tags=$(echo ${{ matrix.PUSH_TAGS }} | tr ',' '\n' | xargs -I {} echo "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/gitlab-arm64:{}" | tr '\n' ',')
          ghcr_tags=$(echo ${{ matrix.PUSH_TAGS }} | tr ',' '\n' | xargs -I {} echo "ghcr.io/${{ github.repository_owner }}/gitlab-arm64:{}" | tr '\n' ',')
          echo "push_tags=${dockerio_tags},${ghcr_tags}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.push_tags }}
          platforms: linux/arm64
          build-args: |
            RELEASE_PACKAGE=${{ matrix.RELEASE_PACKAGE }}
            RELEASE_VERSION=${{ matrix.RELEASE_VERSION }}
